"""Subtitle/transcript normalization for video Sources.

The parser accepts common platform subtitle exports (WebVTT and SRT) and
produces deterministic Markdown with timestamped cues. It deliberately does
not download media; acquisition and ASR provenance stay explicit.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from ..common import canonical_body, sha256_bytes

TRANSCRIPT_SCHEMA = "video-transcript/v1"
TIMING_RE = re.compile(
    r"(?P<start>\d{1,2}:\d{2}(?::\d{2})?(?:[.,]\d{3})?)\s+-->\s+"
    r"(?P<end>\d{1,2}:\d{2}(?::\d{2})?(?:[.,]\d{3})?)"
)
TAG_RE = re.compile(r"<[^>]+>")


@dataclass(frozen=True)
class Cue:
    start: str
    end: str
    text: str


def _timestamp(value: str) -> str:
    value = value.replace(",", ".")
    if value.count(":") == 1:
        value = "00:" + value
    hours, minutes, seconds = value.split(":")
    if "." not in seconds:
        seconds += ".000"
    whole, millis = seconds.split(".", 1)
    return f"{int(hours):02d}:{int(minutes):02d}:{int(whole):02d}.{int(millis[:3]):03d}"


def _clean_text(lines: list[str]) -> str:
    text = " ".join(line.strip() for line in lines if line.strip())
    text = TAG_RE.sub("", text)
    return re.sub(r"\s+", " ", text).strip()


def parse_subtitles(data: bytes, suffix: str = ".vtt") -> list[Cue]:
    """Parse VTT/SRT bytes into normalized cues, rejecting bad timings."""
    text = data.decode("utf-8-sig", errors="strict").replace("\r\n", "\n")
    lines = text.replace("\r", "\n").split("\n")
    cues: list[Cue] = []
    index = 0
    while index < len(lines):
        match = TIMING_RE.search(lines[index].strip())
        if not match:
            index += 1
            continue
        start = _timestamp(match.group("start"))
        end = _timestamp(match.group("end"))
        if end < start:
            raise ValueError("transcript_timing_reversed")
        index += 1
        body: list[str] = []
        while index < len(lines) and lines[index].strip():
            body.append(lines[index])
            index += 1
        cue_text = _clean_text(body)
        if cue_text:
            cues.append(Cue(start=start, end=end, text=cue_text))
        index += 1
    if not cues:
        raise ValueError(f"transcript_cues_missing:{suffix.lower()}")
    return cues


def render_transcript(cues: list[Cue]) -> str:
    """Render deterministic, human-readable Markdown from normalized cues."""
    lines = ["# Video transcript", "", "<!-- generated by video-transcript/v1 -->", ""]
    for cue in cues:
        lines.extend((f"### [{cue.start} - {cue.end}]", "", cue.text, ""))
    return canonical_body("\n".join(lines))


def normalize_file(path: Path) -> tuple[str, dict]:
    """Return canonical transcript Markdown and parser metadata."""
    data = path.read_bytes()
    suffix = path.suffix.lower() or ".vtt"
    if suffix not in {".vtt", ".srt"}:
        raise ValueError("transcript_format_unsupported")
    cues = parse_subtitles(data, suffix)
    body = render_transcript(cues)
    return body, {
        "schema_version": TRANSCRIPT_SCHEMA,
        "format": suffix[1:],
        "cue_count": len(cues),
        "input_sha256": sha256_bytes(data),
        "extractor": "video-transcript/1",
    }
